name: build maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        java-package: jdk
        architecture: x64

    - name: Build
      run: mvn -B -DskipTests clean package

    - name: Test
      run: mvn test